spring.application.name=carteira-vacinacao-api

#TODO para desabilitar o login automático por enquanto.
pring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration