spring.application.name=carteira-vacinacao-api

# JWT
jwt.secret=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgdGhhdCBpcyBhdCBsZWFzdCAyNTYgYml0cyBsb25nIGZvciBIUzI1NiBKV1Qgc2lnbmluZw==
jwt.expiration=3600000
# 3600000 = 1 hora em ms; reduza para 900000 (15min) em produção

# Desabilitar auto-config de segurança padrão que interferia na V0
# (agora o SecurityConfiguration assume o controle completo)